{
 "title": "Churn Prediction System",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "dag_id",
    "query": {
     "query": "label_values(dag_run_status,dag_id)"
    }
   },
   { "name": "batch_filename", "query": { "query": "label_values(batch_filename)" } }
  ]
 },
 "panels": [
  {
   "title": "DAG runs (success vs failed)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(dag_run_status{dag_id=\"$dag_id\", status=\"success\"})",
     "legendFormat": "Success"
    },
    {
     "expr": "count(dag_run_status{dag_id=\"$dag_id\", status=\"failed\"})",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Churn rate per batch run",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  prediction_timestamp AS \"time\",\r\n  AVG(predicted_label::float),\r\n  'Churn Rate' AS metric\r\nFROM predictions\r\nGROUP BY prediction_timestamp\r\nORDER BY prediction_timestamp"
    }
   ]
  },
  {
   "title": "Share of drifted features over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  report_timestamp AS \"time\",\r\n  share_drifted_features,\r\n  'Share of drifted features' AS metric\r\nFROM drift_reports"
    }
   ]
  },
  {
   "title": "DAG run duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (dag_run_duration_seconds_bucket{dag_id=\"$dag_id\"}))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (dag_run_duration_seconds_bucket{dag_id=\"$dag_id\"}))",
     "legendFormat": "p95"
    }
   ]
  }
 ]
}