target: Churn
drop:
  - customerID
  - TotalCharges
numeric:
  - tenure
  - MonthlyCharges
  - charges_per_tenure
categorical:
  - gender
  - Partner
  - Dependents
  - PhoneService
  - MultipleLines
  - InternetService
  - OnlineSecurity
  - OnlineBackup
  - DeviceProtection
  - TechSupport
  - StreamingTV
  - StreamingMovies
  - Contract
  - PaperlessBilling
  - PaymentMethod
  - SeniorCitizen
  - tenure_bucket
  - contract_payment
