apiVersion: 1

datasources:
  - name: Postgres
    uid: postgres
    type: postgres
    url: db:5432
    user: ${POSTGRES_USER}
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      database: ${POSTGRES_DB}
      sslmode: disable
      postgresVersion: 1500
    editable: false
